Login Page
B3FC-Innovation-Hub/rosies-recipes-web pull request #2
Opened 2023-07-21 13:52 UTC by NickyPeto

2023-07-25 09:26 UTC, plundell requested changes

2023-07-25 09:26 UTC, plundell commented on src/pages/login/Login.css
> +		background-color: #003c6a;
use variables

2023-07-25 09:26 UTC, plundell commented on src/components/button/Button.css
> +}
```suggestion
}
.button-fab{
    border-radius: 50%;
    #...any other rules specific to FAB
}
```

2023-07-25 09:26 UTC, plundell commented on src/pages/login/Login.tsx
> +		<div className="container">
Add class name for page, so that all css under this page can be targeted specifically. See also comment in Login.css
```suggestion
		<div className="login container">
```

2023-07-25 09:26 UTC, plundell commented on src/pages/login/Login.css
> +.container {
See also login.tsx. 
```suggestion
.login.container,.login .container {
```

2023-07-25 11:18 UTC, NickyPeto commented on src/components/button/Button.css
> +}
Shouldn't I add this when I create the ui kit on a separate branch?

2023-07-25 11:50 UTC, NickyPeto commented
FYI : The commit 9cf742b is wrongly named because it also contains the renamed CSS classes so that each page can be targeted specifically! .

2023-08-02 07:50 UTC, NickyPeto commented on src/components/button/Button.css
> +}
I did this on the ui kit branch instead

2023-08-02 12:00 UTC, plundell requested changes
Snyggt! Enda grejen är namnen på variablerna.

2023-08-02 12:00 UTC, plundell commented on src/index.css
> +	--primary: #00528f;
vissa av de där namnen är förvirrande, t.ex. 'primary' eller 'secondary' eller 'accent' eller 'warn'... jag tror det är bäst att alla colors heter '--color-warn', '--color-primary' etc. 

Ta för vana att göra det överallt, övertydligt... så fonts blir t.ex. '--font-ibm-regular'

2023-08-02 12:28 UTC, plundell approved these changes
Perfect

2023-08-02 12:33 UTC, merged