Login page #2
B3FC-Innovation-Hub/rosies-recipes-web pull request #6
Opened 2023-08-04 07:55 UTC by NickyPeto

This PR covers the implementation of Microsoft Authentication Library. We are going to use this library in order to log in to Rosie.

2023-08-07 13:18 UTC, NickyPeto commented
The error handling can be improved of course, right now we just throw an Error Constructor but we can handle this better later on I think.

2023-08-09 06:37 UTC, plundell requested changes
Nice. Just change some variable names, add some comments, and comment out unused prop

2023-08-09 06:37 UTC, plundell commented on src/context/msal/constants.ts
> +	throw new Error('Some of this values are undefined, please provide a correct value');
Might as well do 2 seperate checks and throw an error saying which variable is undefined and where the Dev can find it on Azure and where they should add it (ie. In the config file)

2023-08-09 06:37 UTC, plundell commented on src/pages/home/Home.tsx
> +	const requests: RedirectRequest = {
This looks like a single request? Why name it plural? Add an online comment if you want to keep it so the next person understands right away

2023-08-09 06:37 UTC, plundell commented on src/pages/home/Home.tsx
> +const Home: React.FC = () => {
I think we should use a naming convention like HomePageFC so it's really clear what it is...

2023-08-09 06:37 UTC, plundell commented on src/pages/home/Home.tsx
> +export default Home;
Add newline

2023-08-09 06:37 UTC, plundell commented on src/routes/Routes.tsx
> +import Home from "../pages/home/Home";
Same thing here, let's name it so it's immediately clear what it is. In general, don't shy away from longer names which are more descriptive but less "pretty"...

2023-08-09 06:37 UTC, plundell commented on src/pages/login/Login.tsx
>  const Login: React.FC = () => {
Don't change Login to LoginPageFC here because it's not part of this branch, but do create a separate PR where you do...

2023-08-09 06:37 UTC, plundell commented on src/types/ButtonProps.ts
> +    onClick?: () => void | Promise<any>; // optional, but recommended to handle async operations
I think we should avoid using <any> as much as possible. If you're not sure what you want this promise to return or how it will be used I suggest you comment out the prop for now and add an online comment saying exactly that: can be added in the future when we have a use case, at which point the resolve type should be specified

2023-08-09 06:37 UTC, plundell commented on src/App.tsx
> +import { pca } from "./context/msal/constants";
Add a comment what msal is

2023-08-09 06:46 UTC, NickyPeto commented on src/pages/login/Login.tsx
>  const Login: React.FC = () => {
Why? This is the Login PR 😄

2023-08-09 06:48 UTC, NickyPeto commented on src/types/ButtonProps.ts
> +    onClick?: () => void | Promise<any>; // optional, but recommended to handle async operations
Yeah I agree and I know using any is a bad practice . I will instead of commenting it out find the exact types that are expected (msal was complaining about the type of promise). If it doesn't work I'll comment it out

2023-08-09 06:55 UTC, NickyPeto commented on src/types/ButtonProps.ts
> +    onClick?: () => void | Promise<any>; // optional, but recommended to handle async operations
**update** Promise<void> works, the mistake was mine because I was not passing the prop correctly @plundell

2023-08-09 07:22 UTC, NickyPeto commented on src/context/msal/constants.ts
> +	throw new Error('Some of this values are undefined, please provide a correct value');
I did this like that since is not a good security practice to disclose which parameter is wrong in an authentication error, but you can tell me what do you think about it . However I can definitely do separate checks for this!

2023-08-09 08:37 UTC, plundell commented on src/context/msal/constants.ts
> +	throw new Error('Some of this values are undefined, please provide a correct value');
If the code runs in the front-end it won't matter since an attacker can just hair execution and try himself. At best that would be classified as "security through obfuscation"...   In other words you're fine to say which variable is missing.

However, we should include build or deploy checks which fail if all relevant configuration is not provided and at that point it's for the dev's eyes only... That will have to be a separate ticket however so leave that for now.

2023-08-09 08:39 UTC, plundell commented on src/pages/login/Login.tsx
>  const Login: React.FC = () => {
Haha, my bad, got them mixed up. I meant don't change the home page one here... But no big deal, let's leave it!

2023-08-09 08:51 UTC, NickyPeto commented on src/pages/login/Login.tsx
>  const Login: React.FC = () => {
No problem!

2023-08-09 08:59 UTC, NickyPeto commented
All changes pushed @plundell ! 👍

2023-08-09 11:36 UTC, plundell commented
Brilliant

2023-08-09 11:40 UTC, merged